const CONFIG = {
    titleWeb: "chúc mừng 8-3 <3",
    introTitle: '',
    introDesc: `Ngày 8/3 đã đến rồi, chúc một nửa xinh đẹp của thế giới luôn thành công và hạnh phúc trong cuộc sống.`,
    btnIntro: '^^HiHi^^',
    title: 'không bt nói gì hơn vì k mua quà cho các bạn đc 🥰',
    desc: 'im sorry',
    btnYes: 'không sao <33',
    btnNo: 'hôm khác bù :3',
    question: 'thế thì đợi tớ về nha <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'okeeeeeeee <33333333',
    mess: 'tớ biết mà 🥰. Yêu các bạn nhiều nhiều 😘😘',
    messDesc: 'Tối chủ nhật 7h, ae đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
}
