const CONFIG = {
    titleWeb: "chúc mừng 8-3 <3",
    introTitle: 'Hoàng Thị Ngọc Hà',
    introDesc: `Ngày 8/3 đã đến rồi, chúc một nửa xinh đẹp của thế giới luôn thành công và hạnh phúc trong cuộc sống. Chúc bé yêu 8-3 vui vẻ hạnh phúc. `,
    btnIntro: '^^HiHi^^',
    title: 'không bt nói gì hơn vì k mua quà cho bạn đc 🥰',
    desc: 'im sorry',
    btnYes: 'không sao <33',
    btnNo: 'hôm khác bù :3',
    question: 'thế thì đợi bé xuống nha <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'yêu bé <333',
    mess: 'tớ biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối thứ 7 tuần sau 7h, mình đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
}
